dataset_path: data
path: checkpoints
seed: 42
# https://zenn.dev/fkubota/articles/2b8d46b11c178ac2fa2d
test: false
num_epoch: 1
num_workers: 2
num_bins: 4
save_name: n001.pth
load_name: None
detail: False
optimizer: adamW
sequenceRecurrent: False
transforms: 
  random_crop: True
data_loader:
  common:
    num_voxel_bins: 15
  train:
    batch_size: 8
    shuffle: false
  test:
    batch_size: 1
    shuffle: false
train:
  no_batch_norm: false
  initial_learning_rate: 0.01
  weight_decay: 0.0001
  epochs: 10
  dropout: 0
